class Api{
    /**域名 */
    static DOMAIN:string="http://m.d.com";
    /**验证码 */
    static VALID_CODE:string="/valid-code";
    /**活动 */
    static ACTIVITY:string="/wap/doc-list-json";
    /**获取活动详细内容 */
    static ACTIVITY_CONTENT:string="/wap/doc-detail";
    /**登录 */
    static LOGIN:string="/wap/login-valid";
    /**发送短信验证码  (type=0&sendType=register&validCode=&phone=11111111111)*/
    static SEND_PHONE_CODE:string="/memreg/resend-phone";
    /**发送邮件验证码  (type=0&sendType=register&validCode=&email=a@b.com)*/
    static SEND_EMAIL_CODE:string="/memreg/send-email";
    /**手机注册 (parentId=204&phone=11111111111&sendCode=aaaa)*/
    static REG_PHONE:string="/memreg/quickreg";
    /**邮箱注册 (parentId=204&email=xx@bb.cc&sendCode=aaaa)*/
    static REG_EMAIL:string="/memreg/quickreg";
    /**账号注册 (parentId=204&parentName=agent001&loginName=abcdef&loginPwd=a1234567&confirmLoginPwd=a1234567&validCode=8384&nickName=&phone=&sendCode=&drawMoneyPwd=&email=&emailCode=&agree=Books)*/
    static REG_ACCOUNT:string="/memreg/save";
    /**签到列表 */
    static SIGN_LIST:string="/wap/signin-record-data";
}